feat: Add possibility to disable Organization
24eme/signaturepdf pull request #53
Opened 2023-03-14 16:22 UTC by xgaia

Bonjour,

Nous avons une instance qui permet de signer des pdf, et nous aimerions garder l'interface simple, sans l'option `Organiser`. J'ai ajouter une entrée dans la config pour désactiver la fonctionnalité.

2023-03-14 16:35 UTC, nchauvat requested changes

2023-03-14 16:35 UTC, nchauvat commented on Dockerfile
> +ENV DISABLE_ORGANIZATION=false
I think ENABLE_ORGANIZATION=true/false would be easier ? Default would be true and you could set it to false in the environment to disable it.

2023-03-17 10:44 UTC, wincelau commented
Merci je viens de merger la PR j'ai un peu amendé ton commit pour que seul les lignes comportement des modifications soit dans le diff : https://github.com/24eme/signaturepdf/commit/c9f0d2502728da0b6eb61b655e465281c69f77f4

C'est OK pour toi ?

À terme je pense que cette option sera remplacée par une liste d'applications, avec un truc du style : 

APPLICATIONS=[SIGNATURE]

Pour pouvoir gérer l'arriver d'autres onglets comme "Metadonnnées" :)

Je pense aussi donner la possibilité de charger un css custom qui pourrait permettre de cacher des onglets ou ajouter son logo.

2023-03-17 23:37 UTC, wincelau commented
J'ai aussi rajouté une option pour permettre de cacher ou changer le PDF de démo : 68be39ed233fe686935792098f1c6375bc621586

2023-05-02 21:32 UTC, closed without merging